// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qauglrdqssnesfdacxfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhdWdscmRxc3NuZXNmZGFjeGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDg4NjMsImV4cCI6MjA3MTYyNDg2M30.32xdv_OPnm0ZGDxOhF6eIIXWzn2ouwAHg7Vo_qjhN6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});